### ISSUE TITLE
[request] add cifs support

### ISSUE THREAD

**Issue by zixijian** [karthik558/MsM-4.14-RyZeN-#1]
i want use cifs to mount my nas disk.
my device is redmi note7 pro violet,Android 10,miui12.
and i have a question,
why i use dmesg shows many:
```
[86058.737842] healthd: Unknown power supply type 'BMS'
[86058.737955] healthd: Unknown power supply type 'Main'
[48900.132432] healthd: Unknown power supply type 'Main'
qcom,rpmh-regulator soc:rpmh-regulator-ldoa12: TCS Busy, retrying RPMH message send
1700000.ad-hoc-bus: TCS Busy, retrying RPMH message send
[54038.050900] msm_bus_device 1700000.ad-hoc-bus: TCS Busy, retrying RPMH message send
[54038.050913] msm_bus_device 1700000.ad-hoc-bus: TCS Busy, retrying RPMH message
```
i compile kernel by myself cant power on,i use clang12+llvm+ld.lld. 
and disable lto can power on.

**Comment by karthik558** [comment]
> i want use cifs to mount my nas disk.
> my device is redmi note7 pro violet,Android 10,miui12.
> and i have a question,
> why i use dmesg shows many:
> 
> ```
> [86058.737842] healthd: Unknown power supply type 'BMS'
> [86058.737955] healthd: Unknown power supply type 'Main'
> [48900.132432] healthd: Unknown power supply type 'Main'
> qcom,rpmh-regulator soc:rpmh-regulator-ldoa12: TCS Busy, retrying RPMH message send
> 1700000.ad-hoc-bus: TCS Busy, retrying RPMH message send
> [54038.050900] msm_bus_device 1700000.ad-hoc-bus: TCS Busy, retrying RPMH message send
> [54038.050913] msm_bus_device 1700000.ad-hoc-bus: TCS Busy, retrying RPMH message
> ```
> 
> i compile kernel by myself cant power on,i use clang12+llvm+ld.lld.
> and disable lto can power on.

i build with LTO and ld.lld no issues here . if i havent build without ld.lld it will not boot
